name: CI/CD with Docker Compose

on:
  push:
    branches: ["main"]

env:
  # CR_PAT: ${{ vars.MY_TOKEN }}
  # REGISTRY: ghcr.io
  # IMAGE_NAME: gael91/app-test
  SERVER_USERNAME_AND_HOST: ${{ vars.SERVER_USERNAME }}@${{ vars.SERVER_HOST }}

jobs:


  build-upload-main:
    name: Build and upload in Main
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          known_hosts: ${{ vars.SERVER_HOST }}

      - name: Generate Docker tag
        run: |
          TAG="${{ github.sha }}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          
      - name: Build web image
        working-directory: ./
        env:
          CLIENT_URL: ${{ secrets.CLIENT_URL_DEV }}
        run: |
          docker build -t ndemin-api-dev:${{ env.TAG }} .
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no "$SERVER_USERNAME_AND_HOST" "echo 'SSH connection successful!' && whoami && pwd"
      # - name: Push web image to remote server
      #   run: |
      #     docker save ndemin-api-dev:${{ env.TAG }} | gzip | ssh -o StrictHostKeyChecking=no "$SERVER_USERNAME_AND_HOST" "gzip -d | docker load -q"
